### PR TITLE
bulkemail sender.py

### PR DESCRIPTION
**Pull request by voidninjaaa-panda**

### CODE REVIEW

**Comment by yash-gulatii** [comment]
Great Work @voidninjaaa-panda!!!!!
Thanks for Contribution.

**Comment by voidninjaaa-panda** [comment]
@yash-gulatii  closed this pr

**Comment by voidninjaaa-panda** [comment]
Thanks. For the response

**Comment by yash-gulatii** [comment]
No Problem @voidninjaaa-panda. 
Thanks to You (Actually I forgot to Merge).
I was busy doing my College Assignments.

**Pull request merged**
