### PR TITLE
Added Image Snipper tool in Python

### PR DESCRIPTION
**Pull request by akash-rajak**
Made a PR for Image Snipper tool in Python.

Do check it out and merge it.

### CODE REVIEW

**Review by voidninjaaa-panda — APPROVED** [review]

**Comment by akash-rajak** [comment]
@voidninjaaa-panda 
Can you add the respective tags and merge it also

**Comment by voidninjaaa-panda** [comment]
I don't have access to merge @yash-gulatii  will do it soon

**Comment by yash-gulatii** [comment]
Thanks @voidninjaaa-panda for approving the pr.

**Comment by yash-gulatii** [comment]
Great Work @akash-rajak!!!
Thanks for the Contribution.

**Pull request merged**
